### ISSUE TITLE
length of the shadow

### ISSUE THREAD

**Issue by tenSunFree** [florent37/LongShadow#4]
How to adjust the length of the shadow?

similar to this effect
![2017-10-29_172958](https://user-images.githubusercontent.com/23090085/32142285-ec2bc03a-bcce-11e7-88a8-51de56cac6d3.jpg)

**Comment by florent37** [comment]
It's notre possible yet

**Comment by florent37** [comment]
you can use : https://github.com/harjot-oberai/Long-Shadows he did a grat implementation 👍
